version: 0.2
#version: 0.2

phases:
    install:
      commands:
        - npm install
      finally:
        - echo 'Completed installing '
    build:
      commands:
        - npm run-script build
        - echo 'Starting to move files'
<<<<<<< HEAD
        - aws s3 sync build s3://smoothflow-prod/developers
=======
        - aws s3 sync build s3://smoothflow-dev/developers
>>>>>>> development_aws
      finally:
        - echo 'Smoothflow Deployement Succeded.'